version: '3.9'

services:  
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=6001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./cert/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=docker
    depends_on:
      - "redis_cache"
    build: .
    ports:
      - "6000:80"
      - "6001:443"
    links:
      - "redis_cache"
    networks:
      - local

  web2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./cert/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=docker
    depends_on:
      - "redis_cache"
    build: .
    ports:
      - "7000:80"
      - "7001:443"
    links:
      - "redis_cache"
    networks:
      - local

  redis_cache:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
      - "6380:6380"
    networks:
      - local

networks:
  local:
    driver: bridge